Revert "Backport regression fixes for 288144143"
This reverts commit 8e5da1b6ce65350187f8791d90cc20090d9227f6.

Breaks build:
vendor/qcom/opensource/commonsys/system/bt/stack/btm/btm_ble.cc:1683:20:
 error: no member named 'is_le_device_encrypted' in 'tBTM_SEC_DEV_REC'

This was a pick from system/bt, but system/bt contains many commits
in stack/btm, which are not present in the qcom version, including
above member of the typedef struct.
The fix of file stack/btm/btm_ble.cc therefore does not apply at all.

The commit however is kind of a "squash" commit coming from AOSP,
hence the fix for the 2nd file still applies, which will be pushed
as a separate commit.

Change-Id: Ie776e9f140eef7b4cd6ef5a9edbecc55d8154f48